package click.cayenne.entity.auto;

import java.util.List;

/** 
 * Class _Project was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually, 
 * since it may be overwritten next time code is regenerated. 
 * If you need to make any customizations, please use subclass. 
 */
public class _Project extends org.objectstyle.cayenne.CayenneDataObject {

    private static final long serialVersionUID = 5214199287275214498L;
    
    public static final String NAME_PROPERTY = "name";
    public static final String DEPARTMENT_PROPERTY = "department";
    public static final String MANAGER_PROPERTY = "manager";
    public static final String MEMBERS_PROPERTY = "members";

    public static final String PROJECT_ID_PK_COLUMN = "project_id";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void setDepartment(click.cayenne.entity.Department department) {
        setToOneTarget("department", department, true);
    }

    public click.cayenne.entity.Department getDepartment() {
        return (click.cayenne.entity.Department)readProperty("department");
    } 
    
    
    public void setManager(click.cayenne.entity.Person manager) {
        setToOneTarget("manager", manager, true);
    }

    public click.cayenne.entity.Person getManager() {
        return (click.cayenne.entity.Person)readProperty("manager");
    } 
    
    
    public void addToMembers(click.cayenne.entity.Person obj) {
        addToManyTarget("members", obj, true);
    }
    public void removeFromMembers(click.cayenne.entity.Person obj) {
        removeToManyTarget("members", obj, true);
    }
    public List getMembers() {
        return (List)readProperty("members");
    }
    
    
}
