package net.sf.click.examples.domain.auto;

/**
 * Class _Client was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public class _Client extends net.sf.click.examples.domain.BaseEntity {

    private static final long serialVersionUID = 1L;

    public static final String ACTIVE_PROPERTY = "active";
    public static final String DATE_JOINED_PROPERTY = "dateJoined";
    public static final String EMAIL_PROPERTY = "email";
    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String LAST_NAME_PROPERTY = "lastName";
    public static final String TITLE_PROPERTY = "title";
    public static final String ADDRESS_PROPERTY = "address";

    public static final String ID_PK_COLUMN = "id";

    public void setActive(Boolean active) {
        writeProperty("active", active);
    }
    public Boolean getActive() {
        return (Boolean)readProperty("active");
    }


    public void setDateJoined(java.util.Date dateJoined) {
        writeProperty("dateJoined", dateJoined);
    }
    public java.util.Date getDateJoined() {
        return (java.util.Date)readProperty("dateJoined");
    }


    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }


    public void setFirstName(String firstName) {
        writeProperty("firstName", firstName);
    }
    public String getFirstName() {
        return (String)readProperty("firstName");
    }


    public void setLastName(String lastName) {
        writeProperty("lastName", lastName);
    }
    public String getLastName() {
        return (String)readProperty("lastName");
    }


    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }


    public void setAddress(net.sf.click.examples.domain.Address address) {
        setToOneTarget("address", address, true);
    }

    public net.sf.click.examples.domain.Address getAddress() {
        return (net.sf.click.examples.domain.Address)readProperty("address");
    }


}
