package net.sf.click.examples.domain.auto;

import java.util.List;

/**
 * Class _Address was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public class _Address extends net.sf.click.examples.domain.BaseEntity {

    private static final long serialVersionUID = 1L;

    public static final String LINE1_PROPERTY = "line1";
    public static final String LINE2_PROPERTY = "line2";
    public static final String POST_CODE_PROPERTY = "postCode";
    public static final String STATE_PROPERTY = "state";
    public static final String SUBURB_PROPERTY = "suburb";
    public static final String CLIENT_PROPERTY = "client";

    public static final String ID_PK_COLUMN = "id";

    public void setLine1(String line1) {
        writeProperty("line1", line1);
    }
    public String getLine1() {
        return (String)readProperty("line1");
    }


    public void setLine2(String line2) {
        writeProperty("line2", line2);
    }
    public String getLine2() {
        return (String)readProperty("line2");
    }


    public void setPostCode(String postCode) {
        writeProperty("postCode", postCode);
    }
    public String getPostCode() {
        return (String)readProperty("postCode");
    }


    public void setState(String state) {
        writeProperty("state", state);
    }
    public String getState() {
        return (String)readProperty("state");
    }


    public void setSuburb(String suburb) {
        writeProperty("suburb", suburb);
    }
    public String getSuburb() {
        return (String)readProperty("suburb");
    }


    public void addToClient(net.sf.click.examples.domain.Client obj) {
        addToManyTarget("client", obj, true);
    }
    public void removeFromClient(net.sf.click.examples.domain.Client obj) {
        removeToManyTarget("client", obj, true);
    }
    public List getClient() {
        return (List)readProperty("client");
    }


}
