package net.sf.click.examples.domain.auto;

/**
 * Class _CourseBooking was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public class _CourseBooking extends net.sf.click.examples.domain.BaseEntity {

    private static final long serialVersionUID = 1L;

    public static final String BOOKING_DATE_PROPERTY = "bookingDate";
    public static final String BOOKING_NOTES_PROPERTY = "bookingNotes";
    public static final String COURSE_TYPE_PROPERTY = "courseType";
    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String CUSTOMER_ID_PROPERTY = "customerId";

    public static final String ID_PK_COLUMN = "id";

    public void setBookingDate(java.util.Date bookingDate) {
        writeProperty("bookingDate", bookingDate);
    }
    public java.util.Date getBookingDate() {
        return (java.util.Date)readProperty("bookingDate");
    }


    public void setBookingNotes(String bookingNotes) {
        writeProperty("bookingNotes", bookingNotes);
    }
    public String getBookingNotes() {
        return (String)readProperty("bookingNotes");
    }


    public void setCourseType(String courseType) {
        writeProperty("courseType", courseType);
    }
    public String getCourseType() {
        return (String)readProperty("courseType");
    }


    public void setCreatedAt(java.util.Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public java.util.Date getCreatedAt() {
        return (java.util.Date)readProperty("createdAt");
    }


    public void setCustomerId(Integer customerId) {
        writeProperty("customerId", customerId);
    }
    public Integer getCustomerId() {
        return (Integer)readProperty("customerId");
    }


}
