package net.sf.click.examples.domain.auto;

/**
 * Class _SystemCode was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public class _SystemCode extends net.sf.click.examples.domain.BaseEntity {

    private static final long serialVersionUID = 1L;

    public static final String LABEL_PROPERTY = "label";
    public static final String NAME_PROPERTY = "name";
    public static final String ORDER_BY_PROPERTY = "orderBy";
    public static final String VALUE_PROPERTY = "value";

    public static final String ID_PK_COLUMN = "id";

    public void setLabel(String label) {
        writeProperty("label", label);
    }
    public String getLabel() {
        return (String)readProperty("label");
    }


    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }


    public void setOrderBy(Integer orderBy) {
        writeProperty("orderBy", orderBy);
    }
    public Integer getOrderBy() {
        return (Integer)readProperty("orderBy");
    }


    public void setValue(String value) {
        writeProperty("value", value);
    }
    public String getValue() {
        return (String)readProperty("value");
    }


}
