package net.sf.click.examples.domain.auto;

/**
 * Class _User was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public class _User extends net.sf.click.examples.domain.BaseEntity {

    private static final long serialVersionUID = 1L;

    public static final String EMAIL_PROPERTY = "email";
    public static final String FULLNAME_PROPERTY = "fullname";
    public static final String PASSWORD_PROPERTY = "password";
    public static final String USERNAME_PROPERTY = "username";

    public static final String ID_PK_COLUMN = "id";

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }


    public void setFullname(String fullname) {
        writeProperty("fullname", fullname);
    }
    public String getFullname() {
        return (String)readProperty("fullname");
    }


    public void setPassword(String password) {
        writeProperty("password", password);
    }
    public String getPassword() {
        return (String)readProperty("password");
    }


    public void setUsername(String username) {
        writeProperty("username", username);
    }
    public String getUsername() {
        return (String)readProperty("username");
    }


}
