package org.apache.click.examples.domain.auto;

import java.util.List;

/** Class _Student was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually,
  * since it may be overwritten next time code is regenerated.
  * If you need to make any customizations, please use subclass.
  */
public class _Student extends org.apache.click.examples.domain.BaseEntity {

    public static final String NAME_PROPERTY = "name";
    public static final String COURSES_PROPERTY = "courses";
    public static final String STUDENT_HOUSE_PROPERTY = "studentHouse";

    public static final String ID_PK_COLUMN = "id";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }


    public void addToCourses(org.apache.click.examples.domain.Course obj) {
        addToManyTarget("courses", obj, true);
    }
    public void removeFromCourses(org.apache.click.examples.domain.Course obj) {
        removeToManyTarget("courses", obj, true);
    }
    public List getCourses() {
        return (List)readProperty("courses");
    }


    public void setStudentHouse(org.apache.click.examples.domain.StudentHouse studentHouse) {
        setToOneTarget("studentHouse", studentHouse, true);
    }

    public org.apache.click.examples.domain.StudentHouse getStudentHouse() {
        return (org.apache.click.examples.domain.StudentHouse)readProperty("studentHouse");
    }


}
