package org.apache.click.examples.domain.auto;

import java.util.List;

/** Class _StudentHouse was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually,
  * since it may be overwritten next time code is regenerated.
  * If you need to make any customizations, please use subclass.
  */
public class _StudentHouse extends org.apache.click.examples.domain.BaseEntity {

    public static final String NAME_PROPERTY = "name";
    public static final String STUDENT_PROPERTY = "student";

    public static final String ID_PK_COLUMN = "id";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }


    public void addToStudent(org.apache.click.examples.domain.Student obj) {
        addToManyTarget("student", obj, true);
    }
    public void removeFromStudent(org.apache.click.examples.domain.Student obj) {
        removeToManyTarget("student", obj, true);
    }
    public List getStudent() {
        return (List)readProperty("student");
    }


}
