package org.springframework.samples.petclinic.model.auto;

import java.util.List;

/** Class _Owner was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Owner extends org.springframework.samples.petclinic.model.Entity {

    public static final String ADDRESS_PROPERTY = "address";
    public static final String CITY_PROPERTY = "city";
    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String LAST_NAME_PROPERTY = "lastName";
    public static final String TELEPHONE_PROPERTY = "telephone";
    public static final String PETS_PROPERTY = "pets";

    public static final String ID_PK_COLUMN = "ID";

    public void setAddress(String address) {
        writeProperty("address", address);
    }
    public String getAddress() {
        return (String)readProperty("address");
    }
    
    
    public void setCity(String city) {
        writeProperty("city", city);
    }
    public String getCity() {
        return (String)readProperty("city");
    }
    
    
    public void setFirstName(String firstName) {
        writeProperty("firstName", firstName);
    }
    public String getFirstName() {
        return (String)readProperty("firstName");
    }
    
    
    public void setLastName(String lastName) {
        writeProperty("lastName", lastName);
    }
    public String getLastName() {
        return (String)readProperty("lastName");
    }
    
    
    public void setTelephone(String telephone) {
        writeProperty("telephone", telephone);
    }
    public String getTelephone() {
        return (String)readProperty("telephone");
    }
    
    
    public void addToPets(org.springframework.samples.petclinic.model.Pet obj) {
        addToManyTarget("pets", obj, true);
    }
    public void removeFromPets(org.springframework.samples.petclinic.model.Pet obj) {
        removeToManyTarget("pets", obj, true);
    }
    public List getPets() {
        return (List)readProperty("pets");
    }
    
    
}
