package org.springframework.samples.petclinic.model.auto;

import java.util.List;

/** Class _Pet was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Pet extends org.springframework.samples.petclinic.model.Entity {

    public static final String BIRTH_DATE_PROPERTY = "birthDate";
    public static final String NAME_PROPERTY = "name";
    public static final String OWNER_PROPERTY = "owner";
    public static final String TYPE_PROPERTY = "type";
    public static final String VISITS_PROPERTY = "visits";

    public static final String ID_PK_COLUMN = "ID";

    public void setBirthDate(java.util.Date birthDate) {
        writeProperty("birthDate", birthDate);
    }
    public java.util.Date getBirthDate() {
        return (java.util.Date)readProperty("birthDate");
    }
    
    
    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void setOwner(org.springframework.samples.petclinic.model.Owner owner) {
        setToOneTarget("owner", owner, true);
    }

    public org.springframework.samples.petclinic.model.Owner getOwner() {
        return (org.springframework.samples.petclinic.model.Owner)readProperty("owner");
    } 
    
    
    public void setType(org.springframework.samples.petclinic.model.PetType type) {
        setToOneTarget("type", type, true);
    }

    public org.springframework.samples.petclinic.model.PetType getType() {
        return (org.springframework.samples.petclinic.model.PetType)readProperty("type");
    } 
    
    
    public void addToVisits(org.springframework.samples.petclinic.model.Visit obj) {
        addToManyTarget("visits", obj, true);
    }
    public void removeFromVisits(org.springframework.samples.petclinic.model.Visit obj) {
        removeToManyTarget("visits", obj, true);
    }
    public List getVisits() {
        return (List)readProperty("visits");
    }
    
    
}
